### ISSUE TITLE
Importing `gribapi` before `eccodes` fails due to a circular import

### ISSUE THREAD

**Issue by peterazmanov** [ecmwf/eccodes-python#116]
### What happened?

I use `gribapi` module directly without importing `eccodes` first, after upgrade from 1.7.1->any recent version, the import fails.

### What are the steps to reproduce the bug?

```sh
pip install eccodes
python -c "import gribapi"
```

### Version

2.39.1

### Platform (OS and architecture)

Ubuntu 24.04 (6.8.0-50-generic, x86_64)

### Relevant log output

```shell
cannot import name 'CODES_FEATURES_ALL' from partially initialized module 'gribapi' (most likely due to a circular import) (<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/__init__.py)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/__init__.py", line 13, in <module>
    from .gribapi import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/gribapi.py", line 34, in <module>
    from gribapi.errors import GribInternalError
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/errors.py", line 16, in <module>
    from .bindings import ENC, ffi, lib
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/bindings.py", line 102, in <module>
    library_path = find_binary_libs("eccodes")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/bindings.py", line 81, in find_binary_libs
    from eccodes._eccodes import versions as _versions
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/eccodes/__init__.py", line 13, in <module>
    from .eccodes import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/eccodes/eccodes.py", line 12, in <module>
    from gribapi import (
ImportError: cannot import name 'CODES_FEATURES_ALL' from partially initialized module 'gribapi' (most likely due to a circular import) (<path-to-venv>/eccodes2-Lqr16Bgk-py3.12/lib/python3.12/site-packages/gribapi/__init__.py)
```

**Comment by shahramn** [comment]
Thank you for reporting this. We will work on a fix.
In the meantime, this may be a good opportunity to start using the new API. So instead of:
import gribapi
grib_get()/grib_set()

use:
import eccodes
codes_get()/codes_set()
etc
